# @package _global_


env:
  name: CF_Env
  replay_mem: 10000
  initial_mem: 2000
  eps_steps: 200
  learn_episodes: 1000

expert:
  demos: 500
  subsample_freq: 5

agent:
  name: sac
  init_temp: 1e-1

double_q_critic:
  _target_: agent.sac_models.SingleQCritic