# @package _global_


env:
  name: CF_Env
  replay_mem: 10000
  initial_mem: 2000
  eps_steps: 200
  learn_episodes: 550

expert:
  demos: 100
  subsample_freq: 4

agent:
  name: sac
  init_temp: 1e-2

double_q_critic:
  _target_: agent.sac_models.SingleQCritic